### ISSUE TITLE
Flashing superuser.zip makes OmniROM unbootable

### ISSUE THREAD

**Issue by Iey4iej3** [phhusson/super-bootimg#24] opened 2016-08-23 04:23 UTC
ROM: OmniROM 6.0.1 nightly (espressowifi)
Device: Samsung Galaxy Tab 2, p3110

logcat:
[logcat.txt](https://github.com/phhusson/super-bootimg/files/431676/logcat.txt)
logs from TWRP:
[recovery.txt](https://github.com/phhusson/super-bootimg/files/431677/recovery.txt)

**Comment by hughdavenport** [comment] 2016-09-04 21:11
Hey @FrankEular, I think I have a similar issue with paranoid android on my oneplus3. How did you get the logcat.txt when it didn't boot? I can't see adb connection while boot is attempting.

Cheers,

Hugh

**Comment by phhusson** [comment] 2016-09-04 21:25
@hughdavenport you would need to make an eng boot.img from paranoid sources, so that you get ADB straight from device booting, apply the superuser.zip and boot to get the logs

**Comment by hughdavenport** [comment] 2016-09-04 22:14
So from the sources? Not just the downloaded flashable zip for pa? Are there any instructions for that or is that something i should ask pa ppl for?

Btw love the project. Needs to be open source :-)

**Comment by phhusson** [comment] 2016-09-04 22:32
No clue, I don't know how to build Paranoid Android, I can try to build it myself if you need.

**Comment by hughdavenport** [comment] 2016-09-05 09:15
Ok, got logs, this repeats over and over on the bad boot.

```
09-05 21:11:28.645  1054  1054 I InstallerConnection: connecting...
09-05 21:11:28.645  1054  1054 I InstallerConnection: disconnecting...
09-05 21:11:28.645  1054  1054 E InstallerConnection: connection failed
09-05 21:11:28.645  1054  1054 W InstallerConnection: installd not ready
09-05 21:11:28.720   579   703 E slim_daemon: [NDK] bindNDKSensors: Sensor server is unavailable.
0
```

[good-boot-logcat.txt](https://github.com/phhusson/super-bootimg/files/454686/good-boot-logcat.txt) <- before rooting, successful boot

[recovery.log.txt](https://github.com/phhusson/super-bootimg/files/454692/recovery.log.txt) <- rooting

[rooted-boot-logcat.txt](https://github.com/phhusson/super-bootimg/files/454687/rooted-boot-logcat.txt) <- after rooting the boot img

Tested earlier and works fine with CM.

Is there anything more I can do to test? Any idea where I can start debugging more?

Cheers,

Hugh

**Comment by phhusson** [comment] 2016-09-05 10:06
Interesting, seems to be the same problem as OmniROM

**Comment by hughdavenport** [comment] 2016-09-05 20:32
Weird. Omni worked for me on my nexus 5 but doesn't have a release for oneplus 3 so can't try that. I could try. PA on my nexus if you want?

Any ideas on what the problem is? Seems like a weird unrelated thing to hang on lol, the good boot did have that line a few times just not hanging on it

**Comment by phhusson** [comment] 2016-09-05 22:45
Root with omni on hammerhead works for you?!?
The exact same thing didn't work for me... 
Could you tell me which version you tested works?

I think it might be related to init.rc editing. Could be the flash_recovery thing, the on init chmod 0755 /sbin, or a missing \n before the declaration of the su service

**Comment by hughdavenport** [comment] 2016-09-06 19:40
![screenshot_20160907-073720](https://cloud.githubusercontent.com/assets/1222607/18288104/303383d4-74ce-11e6-8dc2-124de257c29f.png)
![screenshot_20160907-073725](https://cloud.githubusercontent.com/assets/1222607/18288110/383b21cc-74ce-11e6-96ef-05fe8d3db104.png)
![screenshot_20160907-073819](https://cloud.githubusercontent.com/assets/1222607/18288124/4069878a-74ce-11e6-99d9-bcf10a27b612.png)
![screenshot_20160907-073844](https://cloud.githubusercontent.com/assets/1222607/18288132/4a177896-74ce-11e6-9a5a-3cd9fda6e39c.png)

**Comment by hughdavenport** [comment] 2016-09-06 19:42
Cant recall what version I initially flashed but this is my current setup. I cant flash the zip and have to do the image manually which i guess is based off another roms img as i didnt pull the boot img off device first.

In process of setting up my new phone but after I'm done I'm happy to test a bunch of different things on the n5

**Comment by phhusson** [comment] 2016-09-23 18:38
Fixed in https://github.com/phhusson/super-bootimg/commit/eaaefa73fffa1c5dba5f4b0d87c519aa6b5c2228

**Closed as completed** 2016-09-23 18:40 UTC
